addon/components/link/component.ts
tests/helpers/wait-for-error.ts
tests/integration/components/link-test.ts

fix: make `<Link>` inert for `setupRenderingTest`

---

README.md
addon/components/link/template.hbs
addon/helpers/link.ts
addon/services/link-manager.ts
tests/acceptance/link-test.ts

feat: add `fromURL`

---

addon/helpers/link.ts

The code was normalizing a missing `models` argument to `models: []` meaning the `cacheKey` for `TestLink`s created via `linkFor` was different from the `cacheKey` for `TestLink`s created via the `test` helper.

Fix models normalization in link helper

---

addon/link.ts

`currentURL` appears to update when the transition starts, but not anymore when it has ended. This leads to `isActive` not updating correctly if the `model()` hook is taking too long to load data. The `currentTransitionStack` however is changing in the `routeDidChange` event handler, which ensures that `isActive` (and friends) are updating at the right time.
If I understand the issue correctly, this should resolve #42.

fix(Link): Use `currentTransitionStack` to enable auto-tracking

---

addon/link.ts

Check `button` property and modifier key states before calling `preventDefault()`

---

addon/helpers/link.ts
package.json
yarn.lock

Caused by https://github.com/emberjs/ember.js/pull/19273.
Original implementation is technically correct and ES standard compliant, but not really clean. The explicit check solves both issues.
---
Latest canary is still broken, because of https://github.com/emberjs/ember.js/pull/19080.
The `Router` is now implicitly initialized whenever `_router` is accessed.

fix: add support for Ember 3.23.0

---

addon/link.ts

Unfortunately, I screwed up when I implemented #473 😞 
Before all of this, when you Cmd+Click a link it would open the link in the same tab by doing `transitionTo()` and calling `preventDefault()`.
After #473, it would open the link in a new tab, due to the skipped `preventDefault()`, but it would also navigate to the link in the current tab due to the `transitionTo()` call that is still happening.
This PR changes the code to skip both `preventDefault()` **and** `transitionTo()` if we detect that the user used a modifier key or a non-primary mouse button. This results in the link only being opened in the new tab, but the current tab staying on the same page.

fix: prevent `super.transitionTo()` call when Cmd+Click is used

---

tests/acceptance/link-test.ts
tests/dummy/app/router.ts

Apparently these route defs persist between calls, even between separate tests. We can instead defined them in the dummy application route and use this fixed set of routes.

tests/acceptance: Avoid multiple `Router.map()` calls

---

.github/workflows/ci.yml
config/ember-try.js

This PR temporarily disables the broken ember-try scenarios until we have fixed compatibility with Ember 3.24 and above, and it adds two new scenarios for the 3.16/20 LTS releases.

Adjust CI jobs

---

tests/dummy/app/router.ts
tests/integration/components/link-test.ts

When a component is only used in subroutes of a route with a dynamic segment then a link in that component does not need to specifically set that dynamic segment. With Ember 3.23 and below such links in rendering tests will be treated just like other links: with an empty `href`.

tests/components/link: Add "incomplete model" test

---

tests/integration/components/link-test.ts

juuuust to make sure we don't break anything when we implement Ember 3.24 compatibility 😉

tests/components: Run tests with and without the `setupLink()` test helper

---

.github/workflows/ci.yml
addon-test-support/setup-link.ts
addon/services/link-manager.ts
config/ember-try.js
package.json
yarn.lock

This PR fixes the compatibility with Ember.js 3.24 and above, specifically compatibility with https://github.com/emberjs/ember.js/pull/19080. The two primary changes are:
- `setupLink()` is now allowed to be used even if the router is already set up
- we ensure that the routing layer is fully set up (see `isRouterInitialized`) by looking at the `currentURL` property of the router service
This PR also re-enables the temporarily disabled CI jobs and adds another explicit one for the 3.24 LTS release.

Fix Ember 3.24 compatibility

---

addon/helpers/link.ts
addon/services/link-manager.ts

a "pram" is something slightly different...... 😂

services/link-manager: Fix typo in `getLinkParamsFromURL()` method name

---

addon/services/link-manager.ts
tests/integration/components/link-test.ts

As the code comment says: as soon as you use a `Link` component we internally try to figure out if the router was initialized and if we do that by accessing `currentURL` on the public `router` service, this causes the router to initialize as an unintended side-effect. This can cause issues for any following `LinkTo` components which deal with incomplete route models, as can be seen in the provided regression test.
This PR works around the problem by accessing the `currentURL` property on the private `router` instead, inspired by the `currentURL()` test helper (see https://github.com/emberjs/ember-test-helpers/blob/v2.1.4/addon-test-support/@ember/test-helpers/setup-application-context.ts#L180). This does not cause the router to initialize and thus avoids the problem mentioned above.

fix(link-manager): Use private router API to query `currentURL` in a side-effect-free way

---

.npmignore

I noticed a `yarn-error.log` file was published. Updated/Added some other files as well.

chore(pkg): Avoid publishing unnecessary files

---

.github/workflows/ci.yml
package.json

This should unblock a bunch of the currently failing dependency updates.

chore(pkg): [BREAKING] raise minimum Node to v12

---

addon-test-support/-private/services/test-instrumented-link-manager.ts
package.json
tests/unit/test-helpers/test-instrumented-link-manager-test.ts
yarn.lock

The link cache was intended to ensure that calling `createUILink()` with the same parameters would return the exact same instance as for earlier calls. The advantages from doing this are very small though and were causing us to need the `ember-auto-import` dependency (for `fast-json-stable-stringify`), which in turn causes us to not be compatible with Ember.js 4 at the moment. Additionally, #573 made the cache more complicated or not work at all, because passed-in functions/actions can't be serialized to JSON as a cache key.
This PR removes the link cache to resolve all of the above issues. As some apps or test suites might be relying on the current behavior, this PR is flagged as "breaking", although it should most likely not break anything for the majority of apps.

refactor(test-helpers): [BREAKING] remove link cache

---

.eslintrc.js
package.json
yarn.lock

ESLint natively does not understand decorators and `babel-eslint` is deprecated in favor of `@babel/eslint-parser`
This should unblock #628

chore(eslint): use `@babel/eslint-parser`

---

package.json
yarn.lock

This should hopefully unblock the lockfile update PR (#661) :)

chore(deps): pin `prettier` to v2.2.1

---

.github/workflows/release.yml
package.json

This PR introduces a `Release` workflow on GitHub Actions, which is triggered when a `vX.Y.Z` tag is pushed to the repository. `release-it` is configured so that it does not run `npm publish` itself, but only pushes the tag to the repository.

Release via CI

---

package.json
pnpm-lock.yaml

This was originally introduced with a `~` constraint, but since there is no obvious reason against using the more regular `^` constraint, this PR adjusts the dependency declaration accordingly.

Adjust `@glimmer/tracking` dependency to use semver

---

addon/index.ts

Fix exporting `LinkParams` and `UILinkParams` types

---

ember-link/README.md

I'm adding this change because the `ember-engines-router-service` is the addon most updated with the Ember Router Service API.

docs: Update readme with the latest engines router service

---

ember-link/package.json
package.json
test-app/package.json

As this is the version they added support for: `import.meta.dirname` and `import.meta.filename`
See https://nodejs.org/en/blog/release/v20.11.0

Increase Support for Node Version to 20.11
